#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1472236029                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Having troubles falling asleep? Fighting insomnia? Trying to have small children falling asleep?
We can help you relax and unwind with nature sounds or white noises to finally get you the rest you deserve.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Marcio                                
your_link                                 :
your_city                                 :                                 
email_address                             :
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : ambient_app
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Find sleep
    description                           : Ease yourself into a slumber, and stay asleep.
    fontawesome_icon_name                 : bed
    
  - title                                 : Create custom soundscapes
    description                           : Fancy a slow lullaby with on a background of waves? Or are you more of a train person? Customize everything to find the perfect ambience to fall asleep
    fontawesome_icon_name                 : heart

  - title                                 : Save your soundscapes
    description                           : Easily go back to your favorite soundscapes
    fontawesome_icon_name                 : save

  - title                                 : Share & Import (Coming Soon)
    description                           : You can share your favorite soundscapes with friends, or use their soundscapes for yourself!
    fontawesome_icon_name                 : share

  - title                                 : Easy to Tweak
    description                           : Nothing is easier than adjusting the volume of every sound in your soundscape.
    fontawesome_icon_name                 : sliders-h
  
  - title                                 : Timer
    description                           : Setup a timer to automatically stop playing when you fall asleep.
    fontawesome_icon_name                 : hourglass-start

  - title                                 : Energy & Data efficient
    description                           : Contrary to other apps we don't make your phone super hot or eat all your data plan
    fontawesome_icon_name                 : leaf
    
  - title                                 : We value your privacy
    description                           : Your data will never be used for any other purpose than using our app
    fontawesome_icon_name                 : user-secret
    

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
